### ISSUE TITLE
Consumption mixes exist with no generation

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#119]
The following consumption mixes lack providers for the generation source or generation processes at all. They seem to be orphan BAs.

Electricity; at grid; consumption mix - Duke Energy Progress West
Electricity; at grid; consumption mix -   Gridforce Energy Management, LLC
Electricity; at grid; consumption mix -   Gridforce South
Electricity; at grid; consumption mix -   New Smyrna Beach, Utilities Commission of
Electricity; at grid; consumption mix -   Western Area Power Administration - Upper Great Plains East

Discussed in #77

**Comment by WesIngwersen** [comment]
Decide as a group to drop these processes when consumption is ~0

**Comment by jump2conclusionsmatt** [comment]
Changes in branch [issues/117_119](https://github.com/USEPA/ElectricityLCI/tree/issues/117_119) begin to address this. There are only two remaining with the current changes. Duke Energy Progress West and New Smyrna Beach. Both of these BAs have 0 or negative generation for 2016 so their emissions are being dropped along the way.

I think there are two options: 
1. the aggregated dataframe could be passed to eia_io_trading.ba_io_trading_model so that we can look for BAs that don't have any emissions associated with them (or we can pass a list of them to remove.
2. Implement some manual edits.

I think it's important to handle these within eia_io_trading so that it's easy to adjust the mixes that have these two as inputs (Southeast FERC and US). Actually with no generation in EIA, I'm not sure how Duke Energy Progress West contributes 0.067% to the national mix.

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt I think I would back option #1.   It sounds like it eia_io_trading needs to rebalance the consumption mix after removing the generation from these two BAs.  This should also be more sustainable in the future so we don't end up having the same issue with the future years of data.

**Comment by jump2conclusionsmatt** [comment]
Option 1 above implemented. Pull Request #135.
