### ISSUE TITLE
Low coal consumption at Duke Energy Florida, Inc.

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#122]
Quantity of coal consumed at duke energy florida per MWh is low relative to other coal plants. Discrepancy between coal consumed and coal received?

**Comment by jump2conclusionsmatt** [comment]
This facility has severely under-reported coal receipts in EIA923 Page 5. 

Potentials solutions:
1. Implement spot fix for this plant - would still need to determine what the right amount of coal is.
2. Use the fuel receipts to determine only the mix of coal coming in. The amount of coal would multiply that mix by the reported EIA923 page 1 data. To make it a tad more difficult, the mixes should be broken out by type of coal. So if a plant is 10% IB-B-U, 15% NA-B-U, 50% PRB-S-S, and 25% GL-L-S, then the weights would be applied as 40% * reported bituminous, 60% * reported bituminous, 100%* reported sub-bit, and 100% * reported lignite.
3. Check coal receipts vs. EIA923 page 1 - and only implement 2 if amounts differ by some amount. Feels far cleaner to me to just do 2.

**Comment by bl-young** [comment]
I'm less familiar with the nuances of the forms off the top of my head, but I would think that 2 would be a good option. It seems that fixing the fuel consumption quantity, based on page 1, is more important than tracking the quantity received, especially given potential changes in stocks. Of course, who knows if other issues will arise upon making that switch.

**Comment by bl-young** [comment]
I guess we can track the differences that result from this after the fact to our coal inputs per MWh we developed for the review of v1.0

**Comment by jump2conclusionsmatt** [comment]
Implemented Solution 2 from above. Duke energy Florida is around the middle of the pack for total coal input. The percent changes for coal inputs at the other balancing authority areas range from -5% to 38%. At the highest level, total coal inputs went down around 7% suggesting that more coal was received at plants than was consumed for electricity in 2016 - a reasonable result.

The biggest thorn in implementing solution 2 is that there are plants that report the use of refined coal (code RC in EIA923), but this isn't a code that is reflected in the coal receipts. The fix for this was to apply the RC amounts against the percent of total plant coal receipts for each individual coal codes.
