### ISSUE TITLE
Question - Aggregating to US provides the same results as aggregating to BA

### ISSUE THREAD

**Issue by TJTapajyoti** [USEPA/ElectricityLCI#158]
@jump2conclusionsmatt From the code, its evident that regional aggregation to US and BA regions follow the same calculation route. Was this intentional? Will we have a method in the future that aggregates to only the US? In this database, we will only have flows of different fuel sources that has been aggregated for all spatial regions. Example - 

_Region FuelCategory FlowNames FlowAmount Emission_factor
US             GAS                CO2               5000                    500_

Additionally @jump2conclusionsmatt How would you recommend to create this kind of aggregated results now?

**Comment by jump2conclusionsmatt** [comment]
Yes - it's intentional because when we started looking at how consumption mixes are calculated, creating mixes based on FERC generation mixes would lead to erroneous results. So the default path creates consumption mixes for BA, FERC, and US. If you need to create generation mixes that will need to be handled manually - again hijacking _gen\_plus\_fuels_ data frame and changing the subregion code to "FERC" or "US" at [this line](https://github.com/USEPA/ElectricityLCI/blob/2232c41f2cb4fd333ad59c8710aa55906e6a7ed3/electricitylci/__init__.py#L89).

**Comment by TJTapajyoti** [comment]
@jump2conclusionsmatt  Thanks.I will close this issue.
