### ISSUE TITLE
Metadata - Assess status of process metadata for BA and FERC models

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#63]
-Determine where metadata is present and where missing
-Recommend update procedure to replace missing data

**Comment by jump2conclusionsmatt** [comment]
All of the fuel/upstream unit processes are missing metadata. I've started making changes to upstreamin_dict.py to implement metadata via yaml. There will be common metadata between the various processes but ultimately there will need to be a separate description for each of the different types since they're sourced from different models using a variety of sources.

There's a similar sort of need for the generation and mix processes, since we're sourcing data from different places. I've made modifications to alt_generation.py to at least have the existing metadata inserted into the processes. We're working on modifying the language to match our methods.

On that note, I'm proposing moving the metadata...data into yaml files for the existing generation processes in lieu of the current csv file. This is mostly for my own sanity since I don't want to have to edit text in tiny excel boxes - should also make everything more readable should someone want this information outside of openLCA.

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt It looks like in olca_schema_genprocess that you were now doing a lot of the work we had in process_dictionary_writer before. Yes a alot of the metadata was in metadata.csv. I agree with moving it to YAML files.  One way to organization it is a base file meta one with info that can apply to all stages meta_all.yml, and then another metadata file that is more specific to stages meta_generation.yml, meta_generation_mix.yml, or even fuels as needed.
