### ISSUE TITLE
Generation processes missing for some eGRID reigons

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#87]
When developing a model build by eGRID reigon, generation processes are missing for Alaska and Hawaii (AKGD, AKMS, HIMS, HIOA), though generation mixes and consumptions mixes are available.

**Comment by jump2conclusionsmatt** [comment]
This is happening [combinator.py](https://github.com/USEPA/ElectricityLCI/blob/master/electricitylci/combinator.py) [fill_nans](https://github.com/USEPA/ElectricityLCI/blob/9ada652786eb1013b1e57d52418448337feaa42b/electricitylci/combinator.py#L40). For running configuration ELCI_3, none of the plants in those subregions get assigned a Balancing Authority Name, EIA_Region, or FERC_Region, Any one of which would cause a row to be dropped at [line 116](https://github.com/USEPA/ElectricityLCI/blob/9ada652786eb1013b1e57d52418448337feaa42b/electricitylci/combinator.py#L116). I think the simplest solution would be to require all of the categories to be NA before a row gets dropped, but I'm unsure how those NAs might affect things downstream. I think that if say we're aggregating on BA rather than eGRID, those rows will still end up getting dropped at a groupby, and if we're aggregating on eGRID, then they'll stay. I'll give it a shot and see what happens.

**Comment by jump2conclusionsmatt** [comment]
There's a [branch ](https://github.com/USEPA/ElectricityLCI/tree/issues/87) for this issue. I committed a couple changes to try and resolve this. One potential issue is that I saw significant increases in CO2 emissions from coal, gas, and mixed plants - on the order of 10% relative to a set of data I had from May 15. I (or someone else) should investigate more to see if the source of increase is previously dropped rows or from something else. If so, why only CO2?

**Comment by jump2conclusionsmatt** [comment]
I ran this again today. I suspect I was running some version of the model without the cems changes imlpemented. I run it now and get very minor changes in ELCI_3 for CAMX, while gaining the ability to get consumption mixes for the regions mentioned above. I'll open a pull request for the changes.
